fileVersion: 1
id: "5"
mappingDefinitions:
  CONFORMED:
    database: TRAINING_DB1
    schema: CUSTOMER_ANALYTICS_CONFORMED1
  STAGE:
    database: TRAINING_DB
    schema: CUSTOMER_ANALYTICS_STAGING
  WAREHOUSE:
    database: TRAINING_DB
    schema: CUSTOMER_ANALYTICS
name: DEV ENVIRONMENT
type: Environment
